### ISSUE TITLE
Conflicting ports with the front-end

### ISSUE THREAD

**Issue by azertyfun** [pebble-dev/rebblestore-api#10]
Currently, both projects use localhost:8080 as the default address, which is fine as long as only one is being worked on at a time.

Furthermore, `boot.go` references https://santoku.adamfourney.com (`STORE_URI`), which doesn't exist right now.

If one of the projects changed its default port to 8081 or something, it would make it easier to work with both projects, and allow to update `STORE_URI` to `localhost:808(0/1)`.

**Comment by sGerli** [comment]
You're right

**Comment by sGerli** [comment]
Although the store url should be store.rebble.io unless you are developing or testing both at the same time
