### ISSUE TITLE
swagger.io compatible API docs

### ISSUE THREAD

**Issue by TheTechmage** [pebble-dev/rebblestore-api#5]
Swagger.io allows developers to view all API endpoints and send requests to them through the web browser. @moejay had some great ideas in https://github.com/pebble-dev/rebble-store/issues/5 that I'm going to see about implementing.

**Comment by Zetaphor** [comment]
Updated link:
https://github.com/pebble-dev/rebble-store/issues/5

**Comment by sGerli** [comment]
We decided not to use Swagger any more
